// GENERATED by scripts/compile-discovery-tools.mjs — do not edit.
// Source: googleads v25 discovery doc (41 read-only tools).
export interface DiscoveryToolDef {
  name: string;
  description: string;
  parameters: { type: "object"; properties: Record<string, unknown>; required: string[] };
  httpMethod: string;
  path: string;
  scopes: string[];
}
export const DISCOVERY_TOOLS: DiscoveryToolDef[] = [
  {
    "name": "listPlannableLocations",
    "description": "Returns the list of plannable locations (for example, countries). List of thrown errors: [AuthenticationError]() [AuthorizationError]() [HeaderError]() [InternalError]() [QuotaError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25:listPlannableLocations",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "listPlannableUserInterests",
    "description": "Returns the list of plannable user interests. A plannable user interest is one that can be targeted in a reach forecast using ReachPlanService.GenerateReachForecast. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [FieldError]() [HeaderError]() [InternalErro [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25:listPlannableUserInterests",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "listPlannableUserLists",
    "description": "Returns the list of plannable user lists with their plannable status. User lists may not be plannable for a number of reasons, including: - They are less than 10 days old. - They have a membership lifespan that is less than 30 days - They have less than 10,000 or more than 700,00 [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25:listPlannableUserLists",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "listBenchmarksSources",
    "description": "Returns the list of benchmarks sources (for example, Industry Verticals). List of thrown errors: [AuthenticationError]() [AuthorizationError]() [FieldError]() [HeaderError]() [InternalError]() [QuotaError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25:listBenchmarksSources",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "listPlannableProducts",
    "description": "Returns the list of per-location plannable YouTube ad formats with allowed targeting. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [HeaderError]() [InternalError]() [QuotaError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25:listPlannableProducts",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "generateConversionRates",
    "description": "Returns a collection of conversion rate suggestions for supported plannable products. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [HeaderError]() [InternalError]() [QuotaError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25:generateConversionRates",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "incentives_fetchIncentive",
    "description": "Returns incentives for a given user. [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {
        "incentiveType": {
          "type": "string",
          "description": "Optional. The type of incentive to get. Defaults to ACQUISITION.",
          "enum": [
            "UNSPECIFIED",
            "UNKNOWN",
            "ACQUISITION"
          ]
        },
        "languageCode": {
          "type": "string",
          "description": "Optional. User's language code. If not provided, the server will default to \"en\". Possible language codes: https://developers.google.com/google-ads/api/data/codes-formats#languages"
        },
        "email": {
          "type": "string",
          "description": "Optional. Email of the user that the requested incentive is meant for. Will be used for channel partners who do NOT use OAuth to authenticate on behalf of user."
        },
        "countryCode": {
          "type": "string",
          "description": "Optional. User's country code. If not provided, the server will default to \"US\". Possible country codes: https://developers.google.com/google-ads/api/data/codes-formats#country_codes"
        }
      },
      "required": []
    },
    "httpMethod": "GET",
    "path": "v25/incentives:fetchIncentive",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "audienceInsights_listInsightsEligibleDates",
    "description": "Lists date ranges for which audience insights data can be requested. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [FieldError]() [HeaderError]() [InternalError]() [QuotaError]() [RangeError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/audienceInsights:listInsightsEligibleDates",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_generateAdGroupThemes",
    "description": "Returns a list of suggested AdGroups and suggested modifications (text, match type) for the given keywords. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [CollectionSizeError]() [HeaderError]() [InternalError]() [QuotaError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:generateAdGroupThemes",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_generateTargetingSuggestionMetrics",
    "description": "Returns potential reach metrics for targetable audiences. This method helps answer questions like \"How many Men aged 18+ interested in Camping can be reached on YouTube?\" List of thrown errors: [AudienceInsightsError]() [AuthenticationError]() [AuthorizationError]() [FieldError]( [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:generateTargetingSuggestionMetrics",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_generateSuggestedTargetingInsights",
    "description": "Returns a collection of targeting insights (e.g. targetable audiences) that are relevant to the requested audience. List of thrown errors: [AudienceInsightsError]() [AuthenticationError]() [AuthorizationError]() [FieldError]() [HeaderError]() [InternalError]() [QuotaError]() [Ran [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:generateSuggestedTargetingInsights",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_suggestBrands",
    "description": "Rpc to return a list of matching brands based on a prefix for this customer. [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:suggestBrands",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_generateBenchmarksMetrics",
    "description": "Returns YouTube advertisement metrics for the given client against industry benchmarks. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [BenchmarksError]() [FieldError]() [HeaderError]() [InternalError]() [QuotaError]() [RangeError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:generateBenchmarksMetrics",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_generateKeywordForecastMetrics",
    "description": "Returns metrics (such as impressions, clicks, total cost) of a keyword forecast for the given campaign. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [CollectionSizeError]() [HeaderError]() [InternalError]() [QuotaError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:generateKeywordForecastMetrics",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_listAccessibleCustomers",
    "description": "Returns resource names of customers directly accessible by the user authenticating the call. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [HeaderError]() [InternalError]() [QuotaError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "GET",
    "path": "v25/customers:listAccessibleCustomers",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_suggestSmartCampaignAd",
    "description": "Suggests a Smart campaign ad compatible with the Ad family of resources, based on data points such as targeting and the business to advertise. [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:suggestSmartCampaignAd",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_generateShareablePreviews",
    "description": "Returns the requested Shareable Preview. [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:generateShareablePreviews",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_generateAudienceCompositionInsights",
    "description": "Returns a collection of attributes that are represented in an audience of interest, with metrics that compare each attribute's share of the audience with its share of a baseline audience. List of thrown errors: [AudienceInsightsError]() [AuthenticationError]() [AuthorizationError [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:generateAudienceCompositionInsights",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_searchAudienceInsightsAttributes",
    "description": "Searches for audience attributes that can be used to generate insights. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [FieldError]() [HeaderError]() [InternalError]() [QuotaError]() [RangeError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:searchAudienceInsightsAttributes",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_generateKeywordHistoricalMetrics",
    "description": "Returns a list of keyword historical metrics. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [CollectionSizeError]() [HeaderError]() [InternalError]() [QuotaError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:generateKeywordHistoricalMetrics",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_suggestTravelAssets",
    "description": "Returns Travel Asset suggestions. Asset suggestions are returned on a best-effort basis. There are no guarantees that all possible asset types will be returned for any given hotel property. [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:suggestTravelAssets",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_generateTrendingInsights",
    "description": "Returns insights for trending content on YouTube. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [FieldError]() [HeaderError]() [InternalError]() [QuotaError]() [RangeError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:generateTrendingInsights",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_generateKeywordIdeas",
    "description": "Returns a list of keyword ideas. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [CollectionSizeError]() [HeaderError]() [InternalError]() [KeywordPlanIdeaError]() [QuotaError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:generateKeywordIdeas",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_generateCreatorInsights",
    "description": "Returns insights for a collection of YouTube Creators and Channels. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [FieldError]() [HeaderError]() [InternalError]() [QuotaError]() [RangeError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:generateCreatorInsights",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_suggestKeywordThemes",
    "description": "Suggests keyword themes to advertise on. [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:suggestKeywordThemes",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_generateInsightsFinderReport",
    "description": "Creates a saved report that can be viewed in the Insights Finder tool. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [FieldError]() [HeaderError]() [InternalError]() [QuotaError]() [RangeError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:generateInsightsFinderReport",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_generateReachForecast",
    "description": "Generates a reach forecast for a given targeting / product mix. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [FieldError]() [HeaderError]() [InternalError]() [QuotaError]() [RangeError]() [ReachPlanError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:generateReachForecast",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_getIdentityVerification",
    "description": "Returns Identity Verification information. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [HeaderError]() [InternalError]() [QuotaError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "GET",
    "path": "v25/customers/{+customerId}/getIdentityVerification",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_suggestSmartCampaignBudgetOptions",
    "description": "Returns BudgetOption suggestions. [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:suggestSmartCampaignBudgetOptions",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_generateAudienceOverlapInsights",
    "description": "Returns a collection of audience attributes along with estimates of the overlap between their potential YouTube reach and that of a given input attribute. List of thrown errors: [AudienceInsightsError]() [AuthenticationError]() [AuthorizationError]() [FieldError]() [HeaderError]( [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}:generateAudienceOverlapInsights",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_experiments_listExperimentAsyncErrors",
    "description": "Returns all errors that occurred during the last Experiment update (either scheduling or promotion). Supports standard list paging. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [HeaderError]() [InternalError]() [QuotaError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {
        "resourceName": {
          "type": "string",
          "description": "Required. The name of the experiment from which to retrieve the async errors."
        },
        "pageToken": {
          "type": "string",
          "description": "Token of the page to retrieve. If not specified, the first page of results will be returned. Use the value obtained from `next_page_token` in the previous response in order to request the next page of"
        },
        "pageSize": {
          "type": "integer",
          "description": "Number of elements to retrieve in a single page. When a page request is too large, the server may decide to further limit the number of returned resources. The maximum page size is 1000."
        }
      },
      "required": [
        "resourceName"
      ]
    },
    "httpMethod": "GET",
    "path": "v25/{+resourceName}:listExperimentAsyncErrors",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_invoices_list",
    "description": "Returns all invoices associated with a billing setup, for a given month. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [FieldError]() [HeaderError]() [InternalError]() [InvoiceError]() [QuotaError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {
        "issueYear": {
          "type": "string",
          "description": "Required. The issue year to retrieve invoices, in yyyy format. Only invoices issued in 2019 or later can be retrieved."
        },
        "billingSetup": {
          "type": "string",
          "description": "Required. The billing setup resource name of the requested invoices. `customers/{customer_id}/billingSetups/{billing_setup_id}`"
        },
        "issueMonth": {
          "type": "string",
          "description": "Required. The issue month to retrieve invoices.",
          "enum": [
            "UNSPECIFIED",
            "UNKNOWN",
            "JANUARY",
            "FEBRUARY",
            "MARCH",
            "APRIL",
            "MAY",
            "JUNE",
            "JULY",
            "AUGUST",
            "SEPTEMBER",
            "OCTOBER",
            "NOVEMBER",
            "DECEMBER"
          ]
        },
        "includeGranularLevelInvoiceDetails": {
          "type": "boolean",
          "description": "Optional. When true, the response will include more granular level invoice details such as campaign level cost breakdown, itemized regulatory costs and adjustments. The default value is false."
        }
      },
      "required": []
    },
    "httpMethod": "GET",
    "path": "v25/customers/{+customerId}/invoices",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_paymentsAccounts_list",
    "description": "Returns all payments accounts associated with all managers between the login customer ID and specified serving customer in the hierarchy, inclusive. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [HeaderError]() [InternalError]() [PaymentsAccountError]() [Q [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "GET",
    "path": "v25/customers/{+customerId}/paymentsAccounts",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_campaignDrafts_listAsyncErrors",
    "description": "Returns all errors that occurred during CampaignDraft promote. Throws an error if called before campaign draft is promoted. Supports standard list paging. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [HeaderError]() [InternalError]() [QuotaError]() [Reque [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {
        "pageToken": {
          "type": "string",
          "description": "Token of the page to retrieve. If not specified, the first page of results will be returned. Use the value obtained from `next_page_token` in the previous response in order to request the next page of"
        },
        "pageSize": {
          "type": "integer",
          "description": "Number of elements to retrieve in a single page. When a page request is too large, the server may decide to further limit the number of returned resources."
        },
        "resourceName": {
          "type": "string",
          "description": "Required. The name of the campaign draft from which to retrieve the async errors."
        }
      },
      "required": [
        "resourceName"
      ]
    },
    "httpMethod": "GET",
    "path": "v25/{+resourceName}:listAsyncErrors",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_smartCampaignSettings_getSmartCampaignStatus",
    "description": "Returns the status of the requested Smart campaign. [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {
        "resourceName": {
          "type": "string",
          "description": "Required. The resource name of the Smart campaign setting belonging to the Smart campaign to fetch the status of."
        }
      },
      "required": [
        "resourceName"
      ]
    },
    "httpMethod": "GET",
    "path": "v25/{+resourceName}:getSmartCampaignStatus",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_batchJobs_listResults",
    "description": "Returns the results of the batch job. The job must be done. Supports standard list paging. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [BatchJobError]() [HeaderError]() [InternalError]() [QuotaError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {
        "resourceName": {
          "type": "string",
          "description": "Required. The resource name of the batch job whose results are being listed."
        },
        "pageToken": {
          "type": "string",
          "description": "Token of the page to retrieve. If not specified, the first page of results will be returned. Use the value obtained from `next_page_token` in the previous response in order to request the next page of"
        },
        "pageSize": {
          "type": "integer",
          "description": "Number of elements to retrieve in a single page. The default and the page_size limit is 1000. A value of 0 or an unset page size will be defaulted to 1000. A page size less than 0 or greater than 1000"
        },
        "responseContentType": {
          "type": "string",
          "description": "The response content type setting. Determines whether the mutable resource or just the resource name should be returned.",
          "enum": [
            "UNSPECIFIED",
            "RESOURCE_NAME_ONLY",
            "MUTABLE_RESOURCE"
          ]
        }
      },
      "required": [
        "resourceName"
      ]
    },
    "httpMethod": "GET",
    "path": "v25/{+resourceName}:listResults",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_googleAds_search",
    "description": "Returns all rows that match the search query. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [ChangeEventError]() [ChangeStatusError]() [ClickViewError]() [HeaderError]() [InternalError]() [QueryError]() [QuotaError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/customers/{+customerId}/googleAds:search",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_operations_get",
    "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service. [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the operation resource."
        }
      },
      "required": [
        "name"
      ]
    },
    "httpMethod": "GET",
    "path": "v25/{+name}",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "customers_operations_list",
    "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`. [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the operation's parent resource."
        },
        "filter": {
          "type": "string",
          "description": "The standard list filter."
        },
        "returnPartialSuccess": {
          "type": "boolean",
          "description": "When set to `true`, operations that are reachable are returned as normal, and those that are unreachable are returned in the ListOperationsResponse.unreachable field. This can only be `true` when read"
        },
        "pageToken": {
          "type": "string",
          "description": "The standard list page token."
        },
        "pageSize": {
          "type": "integer",
          "description": "The standard list page size."
        }
      },
      "required": [
        "name"
      ]
    },
    "httpMethod": "GET",
    "path": "v25/{+name}",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "googleAdsFields_search",
    "description": "Returns all fields that match the search query. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [HeaderError]() [InternalError]() [QueryError]() [QuotaError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {},
      "required": []
    },
    "httpMethod": "POST",
    "path": "v25/googleAdsFields:search",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  },
  {
    "name": "googleAdsFields_get",
    "description": "Returns just the requested field. List of thrown errors: [AuthenticationError]() [AuthorizationError]() [HeaderError]() [InternalError]() [QuotaError]() [RequestError]() [Google Ads API v25, read-only]",
    "parameters": {
      "type": "object",
      "properties": {
        "resourceName": {
          "type": "string",
          "description": "Required. The resource name of the field to get."
        }
      },
      "required": [
        "resourceName"
      ]
    },
    "httpMethod": "GET",
    "path": "v25/{+resourceName}",
    "scopes": [
      "https://www.googleapis.com/auth/adwords"
    ]
  }
];
export const DISCOVERY_VERSION = "v25";
